comfib/comfib/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls')),
]

comfib/services/urls.py
from django.urls import path
from . import views

app_name = "services"
urlpatterns = [
    path('', views.index, name='index'),
    path('creation',views.creation,name='creation'),
    path('createEline',views.createEline,name='createEline'),
    path('report',views.report,name='report'),
    path('all/<int:pk>',views.AllView.as_view(),name='all'),
    path('api/portData',views.get_port_data,name='port_data'),
    path('api/nodes',views.get_nodes,name='get_nodes'),
    path('api/<int:node_id>/ports/',views.get_node_ports,name='get_node_ports'),
    path('api/<int:node_id>/sdps/',views.get_node_sdps,name='get_node_sdps'),
]

comfib/services/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import NullBooleanField
from django.db.models.fields.related import ForeignKey
from django.contrib import admin

# Create your models here.

class Node(models.Model):
    id = models.IntegerField(primary_key=True)
    node_name = models.CharField(max_length=30)
    system_ip = models.CharField(max_length=30)

    def __str__(self):
        return self.node_name

class Port(models.Model):
    node_id = models.ForeignKey(Node, on_delete=models.CASCADE,related_name='ports')
    port_name = models.CharField(max_length=30)

    def __str__(self):
        return "Node:"+ self.node_id.node_name +"-Port: " + str(self.port_name)

class Service(models.Model):
    id = models.IntegerField(primary_key=True)
    service_id_str = models.CharField(max_length=10)
    node_id = models.ForeignKey(Node, on_delete=CASCADE,related_name='services')

    def __str__(self):
        return "Node:"+ self.node_id.node_name +"-Service: " + str(self.service_id_str)


class Sap(models.Model):
    port = models.ForeignKey(Port, on_delete=models.CASCADE,related_name='saps')
    service_id = models.ForeignKey(Service,on_delete=CASCADE,related_name='saps')
    outer_vlan = models.IntegerField(null=True)
    inner_vlan = models.IntegerField(null=True)

    def __str__(self):
        return self.port.port_name +":" + str(self.outer_vlan)

class Sdp(models.Model):
    id = models.IntegerField(primary_key=True)
    from_node = models.ForeignKey(Node, related_name="spds_from", on_delete=models.CASCADE)
    to_node = models.ForeignKey(Node,related_name="sdps_to",on_delete=models.CASCADE)
    
    def __str__(self):
        return "from:"+ self.from_node.node_name +"-to: " + str(self.to_node.node_name)

class SdpBinding(models.Model):
    id = models.IntegerField(primary_key=True)
    sdp_id = models.ForeignKey(Sdp,related_name="bindings",on_delete=CASCADE)
    service = models.ForeignKey(Service,related_name="sdp_bindings",on_delete=CASCADE)
    vc_id = models.IntegerField()

    def __str__(self):
        return "service:"+ self.service.service_id_str +"-spoke: " + str(self.sdp_id) + ":" + str(self.vc_id)

comfib/services/views.py
import os
from django.shortcuts import redirect, render
from django.http import HttpResponse,JsonResponse
from services.srosparser import ServiceSlicing
from .models import Node,Port,Sap,Service,Sdp,SdpBinding
from django.views import generic

# Create your views here.
def index(request):
    nodes = list(Node.objects.all().values())
    return render(request, 'services/index.html',{'nodes':nodes })

def creation(request):
    return render(request,'services/servicecreation.html')

class AllView(generic.DetailView):
    model = Node
    template_name = 'services/all.html'

def createEline(request):
  if request.method == 'POST':
    nodeA = list(Node.objects.filter(id=request.POST['NodeA']).values_list('system_ip',flat=True))[0]
    nodeB = list(Node.objects.filter(id=request.POST['NodeB']).values_list('system_ip',flat=True))[0]
    portA = list(Port.objects.filter(node_id=int(request.POST['NodeA']),id=int(request.POST['PortA'])).values_list('port_name',flat=True))[0]
    portB = list(Port.objects.filter(node_id=int(request.POST['NodeB']),id=int(request.POST['PortB'])).values_list('port_name',flat=True))[0]
    print ("node a:"+nodeA+" nodeB:"+ nodeB + "a: "+portA + "b: "+portB)
    data = {
      'node_a': nodeA,
      'node_b': nodeB,
      'port_a': portA,
      'port_b': portB,
      'vlana':request.POST['VlanA'],
      'vlanb':request.POST['VlanB'],
      'serviceId':request.POST['ServiceId'],
      'sdpa':request.POST['sdpAB'],
      'sdpb':request.POST['sdpBA'],
      'vcid':request.POST['vcId'],
    }
    serviceA = Service(
      id = request.POST['NodeA'] + request.POST['ServiceId'],
      service_id_str =request.POST['ServiceId'],
      node_id = Node.objects.get(id=request.POST['NodeA'])
    )
    serviceA.save()
    serviceB = Service(
      id= request.POST['NodeB'] + request.POST['ServiceId'],
      service_id_str = request.POST['ServiceId'],
      node_id = Node.objects.get(id=request.POST['NodeB'])
    )
    serviceB.save()

    sapA = Sap(
      port = Port.objects.get(id=request.POST['PortA']),
      service_id = Service.objects.get(id=request.POST['NodeA'] + request.POST['ServiceId']),
      outer_vlan = request.POST['VlanA'],
      inner_vlan = 0
    )

    sapA.save()

    sapB = Sap(
      port = Port.objects.get(id=request.POST['PortB']),
      service_id = Service.objects.get(id=request.POST['NodeB'] + request.POST['ServiceId']),
      outer_vlan = request.POST['VlanB'],
      inner_vlan = 0
    )
    sapB.save()

    sdpA = SdpBinding(
      sdp_id = Sdp.objects.get(id=request.POST['sdpAB']),
      vc_id = request.POST['vcId'],
      service = Service.objects.get(id=request.POST['NodeA'] + request.POST['ServiceId']),
    )
    sdpA.save()
    sdpB = SdpBinding(
      sdp_id = Sdp.objects.get(id=request.POST['sdpBA']),
      vc_id = request.POST['vcId'],
      service = Service.objects.get(id=request.POST['NodeA'] + request.POST['ServiceId']),
    )
    sdpB.save()

    return render(request,'services/createEline.html',data)
  else:
    return redirect('services:creation')

def report(request):
    return render(request,'services/report.html')

def get_port_data(request,*args):
    dir_path = os.path.dirname(os.path.realpath(__file__))
    print(dir_path)
    filepath = dir_path + '/configs/'
    data = getSapPerPort(filepath)
    return JsonResponse(data)

def get_node_ports(request,node_id):
  ports = Port.objects.filter(node_id=node_id).values()
  return JsonResponse(list(ports),safe=False)

def get_node_sdps(request,node_id):
  sdps = Sdp.objects.filter(from_node_id=node_id).values()
  return JsonResponse(list(sdps),safe=False)

def get_nodes(request):
  #nodes = Node.objects.all()
  #data = serializers.serialize('json', nodes)
  return JsonResponse(list(Node.objects.all().values()), safe=False)


def groupByPortId(sapList):
  portDict = {}
  for sap in sapList:
    if ":" in sap:
      port = sap.split(":")[0]
      if port in portDict:
        portDict[port] = portDict[port] + 1
      else:
        portDict[port] = 1
    """ else:
      port = sap
      if port in portMap:
        portMap[port] = portMap[port] + 1
      else:
        portMap[port] = 1 """
  portTemp = sorted(portDict, key=portDict.get, reverse=True)
  returnDict = {}
  if len(portTemp) > 10:
    for i in range(0,10):
      returnDict[portTemp[i]] = portDict[portTemp[i]]
  else:
    for i in range(0,len(portTemp)):
      returnDict[portTemp[i]] = portDict[portTemp[i]]
    
  if returnDict:
    return returnDict

def getSapPerPort(folder):
  wholeThing = {}
  listDir = os.listdir(folder)
  dir_path = os.path.dirname(os.path.realpath(__file__))
  for file in listDir:
    with open(dir_path+"/configs/"+file) as f:
        con = f.read()
        conf = ServiceSlicing(con)
        sapList = conf.sap_list_return()
        nodeSap = {'name':conf.host_name(),'systemIp':conf.system_ip_address(),'totalSapCount':len(sapList)}
        grouped = groupByPortId(sapList)
        mergedPortAndNode = {'port':grouped,'node':nodeSap}
        ##sapsDetail = {}
    wholeThing[file]= mergedPortAndNode
  print(wholeThing)  
  return wholeThing

comfib/services/templates/base/css.html
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

comfib/services/templates/base/js.html
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.0/chart.min.js" integrity="sha512-TW5s0IT/IppJtu76UbysrBH9Hy/5X41OTAbQuffZFU6lQ1rdcLHzpU5BzVvr/YFykoiMYZVWlr/PX1mDcfM9Qg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

comfib/services/templates/services/all.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>ComFib Interview</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'services/styles.css' %}">
    <!-- <script src='main.js'></script> -->
    {% include 'base/css.html' %}
    {% include 'base/js.html' %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-left" href="{% url 'services:index' %}"><img src="{% static 'services/img/community-fibre-1.png' %}" height="80px" width="80px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'services:creation' %}"><span class="sr-only">(current)</span>Service Creation </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'services:report' %}">Service Report</a>
                </li>
                </ul>
            </div>
        </nav>
    {% if node %}
    <div class="container">
        <h2>Node {{ node.node_name }} Preview</h2>
        <button type="button" class="btn btn-secondary col-12" data-toggle="collapse" data-target="#ports">Ports</button>
        <div id="ports" class="collapse in col-12">
            <ul>
                {% for port in node.ports.all %}
                <li><p>{{port}} </p>
                {% if port.saps.all %}
                <button type="button" class="btn btn-secondary col-3 btn-sm" data-toggle="collapse" data-target="#saps{{ port.id }}">Port Saps</button>
                <div id="saps{{ port.id }}" class="collapse in">
                    <ul>    
                    {% for sap in port.saps.all%}
                    <li><p>{{sap}} </p></li>
                    {% endfor %}
                    </ul>
                </div>
                {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
        <button type="button" class="btn btn-secondary col-12" data-toggle="collapse" data-target="#services">Services</button>
        <div id="services" class="collapse in col-12">
            <ul>
            {% for service in node.services.all %}
            <li><p>{{service}} </p>
            {% if service.saps.all %}
            <button type="button" class="btn btn-secondary col-3 btn-sm" data-toggle="collapse" data-target="#serviceSaps{{service.id}}">Service Saps</button>
            <div id="serviceSaps{{service.id}}" class="collapse in col-6">
                <ul>    
                {% for sap in service.saps.all%}
                <li><p>{{sap}} </p></li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            {% if service.sdp_bindings.all %}
            <button type="button" class="btn btn-secondary col-3 btn-sm" data-toggle="collapse" data-target="#serviceSdp{{service.id}}">Service Sdps</button>
            <div id="serviceSdp{{service.id}}" class="collapse in col-6">
                <ul>    
                {% for sdp in service.sdp_bindings.all%}
                <li><p>{{sdp}} </p></li>
                {% endfor %}
                </ul>
            </div>
            {% endif %}
            </li>
            {% endfor %}
            </ul>
        </div>
        <button type="button" class="btn btn-secondary col-12" data-toggle="collapse" data-target="#tunnels">Service Tunnels</button>
        <div id="tunnels" class="collapse in col-12">
            <ul>
                {% for sdp in node.spds_from.all %}
                <li><p>Service Tunnel: {{sdp}} </p>
                {% if sdp.bindings.all %}
                <button type="button" class="btn btn-secondary col-3 btn-sm" data-toggle="collapse" data-target="#tunnels{{ sdp.id }}">Tunnel Sdps</button>
                <div id="tunnels{{ sdp.id }}" class="collapse in">
                    <ul>    
                    {% for binding in sdp.bindings.all%}
                    <li><p>{{binding}} </p></li>
                    {% endfor %}
                    </ul>
                </div>
                {% endif %}
                </li>
                {% endfor %}
            </ul>
        </div>
      </div>
    {% else %}
        <p>No  nodes are available.</p>
    {% endif %}

   
</body>
</html> 

comfib/services/templates/services/createEline.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>ComFib Interview</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'services/styles.css' %}">
    <!-- <script src='main.js'></script> -->
    {% include 'base/css.html' %}
    {% include 'base/js.html' %}
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-left" href="{% url 'services:index' %}"><img src="{% static 'services/img/community-fibre-1.png' %}" height="80px" width="80px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'services:creation' %}"><span class="sr-only">(current)</span>Service Creation </a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'services:report' %}">Service Report</a>
        </li>
        </ul>
    </div>
</nav>
    <h2 style="align-self: center;" >You can copy and paste below config to corresponding nodes for service creation</h2>
    <div class='container'>
      <div class='row'>
              <div class='col-6 col-sm-12 col-md-6'>
                <h3>{{node_a}}</h3>
                <h4>Port Config</h4>
                <div>
                  <pre>configure port {{port_a}}</pre>
                  <pre> ethernet</pre>
                  <pre>   mode access</pre>
                  <pre>   encap-type dot1q</pre>
                  <pre>   exit</pre>
                  <pre> no shutdown </pre>
              </div>
              <h4>Service Config</h4>
              <div>
                <pre>configure service epipe {{serviceId}} customer 1 create</pre>
                <pre>sap  {{port_a}}:{{vlana}} create</pre>
                <pre> no shutdown</pre>
                <pre> exit</pre>
                <pre>spoke-sdp  {{sdpa}}:{{vcid}} create</pre>
                <pre> no shutdown</pre>
                <pre> exit</pre>
                <pre>no shutdown</pre>
              </div>
              </div>
              <div class='col-6 col-sm-12 col-md-6'>
                <h3>{{node_b}}</h3>
                <h4>Port Config</h4>
                <div>
                    <pre>configure port {{port_b}}</pre>
                    <pre> ethernet</pre>
                    <pre>   mode access</pre>
                    <pre>   encap-type dot1q</pre>
                    <pre>   exit</pre>
                    <pre> no shutdown </pre>
                </div>
                <h4>Service Config</h4>
                <div>
                  <pre>configure service epipe {{serviceId}} customer 1 create</pre>
                  <pre>sap  {{port_b}}:{{vlanb}} create</pre>
                  <pre> no shutdown</pre>
                  <pre> exit</pre>
                  <pre>spoke-sdp  {{sdpb}}:{{vcid}} create</pre>
                  <pre> no shutdown</pre>
                  <pre> exit</pre>
                  <pre>no shutdown</pre>
                </div>
              </div>
          </div>
  </div>
    {% include 'base/js.html' %} 
    {% block javascript %}
    <script>
    </script>
    {% endblock %}
</body>
</html> 

comfib/services/templates/services/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>ComFib Interview</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'services/styles.css' %}">
    <!-- <script src='main.js'></script> -->
    {% include 'base/css.html' %}
    {% include 'base/js.html' %}
</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-left" href="{% url 'services:index' %}"><img src="{% static 'services/img/community-fibre-1.png' %}" height="80px" width="80px"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'services:creation' %}"><span class="sr-only">(current)</span>Service Creation </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'services:report' %}">Service Report</a>
                </li>
                </ul>
            </div>
        </nav>
    <div class="container">
    <p>This website is created as weekend project to show some talent for Community Fibre interview</p>
    <button type="button" class="btn btn-secondary col-4" data-toggle="collapse" data-target="#techUsed">Tech Used</button>
    <div id="techUsed" class="collapse in col-12">
    <p>CSS,JS,Ajax</p>
    <p>Relational DB Creation</p>
    <p>Python. Django + Parser Module</p>
    <p>Simple API</p>
    <p>Developed related to Network Domain</p>
    <p>Dockerized</p>
    </div>
    </div>
    {% if nodes %}
    <div class="row" style="padding-top: 3rem;">
    {% for node in nodes %}
      <div class="col-sm-12 col-lg-3 col-md-6">
        <div class="card text-white bg-dark">
        <div class="card-body text-white bg-dark">
            <h5 class="card-title">Node:{{ node.node_name}} IP:{{ node.system_ip}}</h5>
            <p class="card-text">See port and service details of {{ node.node_name}}</p>
            <a href="all/{{node.id}}" class="btn btn-secondary">Check inventory on node!</a>
        </div>
      </div>
      </div>
    {% endfor %}
    </div>
    {% endif %}
</body>
</html> 

comfib/services/templates/services/servicecreation.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>ComFib Interview</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' href="{% static 'services/styles.css' %}">
    <!-- <script src='main.js'></script> -->
    {% include 'base/css.html' %}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-left" href="{% url 'services:index' %}"><img src="{% static 'services/img/community-fibre-1.png' %}" height="80px" width="80px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'services:creation' %}"><span class="sr-only">(current)</span>Service Creation </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'services:report' %}">Service Report</a>
            </li>
            </ul>
        </div>
    </nav>
    <!-- {% if services == 'epipe' %}
    <p>Welcome to service creation is found</p>
    {% endif %} -->
    <p>Please select below to create simple eline service between to nodes.</p>
    <form action="{% url 'services:createEline' %}" method="post">
        {% csrf_token %}
        <div class="form-group row">
          <label class="col-4 col-form-label" for="NodeA">Node A</label> 
          <div class="col-8">
            <select id="NodeA" name="NodeA" class="custom-select" required="required" onchange="populatePorts(this,'A')">
                <option value="0">Please select a Node</option>
            </select>
          </div>
        </div>
        <div class="form-group row">
          <label for="NodeB" class="col-4 col-form-label">Node B</label> 
          <div class="col-8">
            <select id="NodeB" name="NodeB" class="custom-select" required="required" onchange="populatePorts(this,'B')">
                <option value="0">Please select a Node</option>
            </select>
          </div>
        </div>
        <div class="form-group row">
            <label for="ServiceId" class="col-4 col-form-label">Service Id</label> 
            <div class="col-8">
              <input type="number" id="ServiceId" min="0" name="ServiceId" class="form-control" required="required">
            </div>
          </div>
        <div class="form-group row">
          <label for="PortA" class="col-4 col-form-label">Port A</label> 
          <div class="col-8">
            <select id="PortA" name="PortA" class="custom-select" required="required" ></select>
          </div>
        </div>
        <div class="form-group row">
          <label for="PortB" class="col-4 col-form-label">Port B</label> 
          <div class="col-8">
            <select id="PortB" name="PortB" class="custom-select" required="required"></select>
          </div>
        </div>
        <div class="form-group row">
          <label class="col-4 col-form-label" for="VlanA">Vlan A</label> 
          <div class="col-8">
            <input id="VlanA" name="VlanA" type="number" max="4095" min="0" class="form-control" required="required">
          </div>
        </div>
        <div class="form-group row">
          <label for="VlanB" class="col-4 col-form-label">Vlan B</label> 
          <div class="col-8">
            <input id="VlanB" name="VlanB" type="number" max="4095" min="0" class="form-control" required="required">
          </div>
        </div>
        <div class="form-group row">
          <label for="sdpAB" class="col-4 col-form-label">SDP A to B</label> 
          <div class="col-8">
            <select id="sdpAB" name="sdpAB"  class="custom-select" required="required"></select>
          </div>
        </div>
        <div class="form-group row">
          <label for="sdpBA" class="col-4 col-form-label">SDP B to A</label> 
          <div class="col-8">
            <select id="sdpBA" name="sdpBA" class="custom-select" required="required"></select>
          </div>
        </div>
        <div class="form-group row">
          <label for="vcId" class="col-4 col-form-label">vcID</label> 
          <div class="col-8">
            <input id="vcId" name="vcId" type="text" class="form-control" required="required">
          </div>
        </div>
        <div class="form-group row">
            <div class="offset-4 col-8">
              <button name="submit" type="submit" class="btn btn-secondary">Submit</button>
            </div>
          </div>
      </form>
    {% include 'base/js.html' %} 
    {% block javascript %}
    <script>
        $.ajax({
            method: "GET",
            url: '/api/nodes',
            success: function(data){
                console.log(data)
                    for(key in data){
                        $('<option>').val(data[key].id).text(data[key].node_name + ":"+ data[key].system_ip).appendTo('#NodeA');
                        $('<option>').val(data[key].id).text(data[key].node_name + ":"+ data[key].system_ip).appendTo('#NodeB');
                    }
            },error: function(error_data){
                console.log("error")
                console.log(error_data)
            }
        });

    function populatePorts(node_id,field){
        console.log(node_id.value)
        $("#Port"+field).empty();
        $.ajax({
            method: "GET",
            url: '/api/'+node_id.value+'/ports',
            success: function(data){
                console.log(data)
                    for(key in data){
                        $('<option>').val(data[key].id).text(data[key].port_name).appendTo('#Port'+field);
                    }
            },error: function(error_data){
                console.log("error")
                console.log(error_data)
            }
        });

        if($('#NodeA').val() !== "0" && $('#NodeB').val() !== "0"){
            var nodeAId = $('#NodeA').val();
            console.log(nodeAId)
            var nodeBId = $('#NodeB').val();
            console.log(nodeBId)
            $("#sdpAB").empty();
            $("#sdpBA").empty();
            $.ajax({
                method: "GET",
                url: '/api/'+nodeAId+'/sdps',
                success: function(data){
                    console.log(data)
                        for(key in data){
                            if(data[key].to_node_id == nodeBId){
                                $('<option>').val(data[key].id).text(data[key].id).appendTo('#sdpAB');
                            }  
                        }
                },error: function(error_data){
                    console.log("error")
                    console.log(error_data)
                }
            });
            
            $.ajax({
                method: "GET",
                url: '/api/'+nodeBId+'/sdps',
                success: function(data){
                    console.log(data)
                        for(key in data){
                            if(data[key].to_node_id == nodeAId){
                                $('<option>').val(data[key].id).text(data[key].id).appendTo('#sdpBA');
                            }  
                        }
                },error: function(error_data){
                    console.log("error")
                    console.log(error_data)
                }
            });

        }
    }

    </script>
    {% endblock %}
</body>
</html> 